version: "3.7"
services:
  nginx:
    image: nginx:consul
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/consul-templates/nginx.conf:ro
    ports:
    - "80:80"
    depends_on:
      - consul
    labels:
      SERVICE_IGNORE: 'yes'
    networks:
      - back-tier

  consul:
    command: -server -bootstrap -advertise ${HOST_IP}
    image: progrium/consul
    labels:
      SERVICE_IGNORE: 'yes'
    ports:
    - "8500:8500"
    networks:
      - back-tier

  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
    - consul
    volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - back-tier

  # http:
  #   image: nginxdemos/hello:latest
  #   labels:
  #     SERVICE_80_NAME: http
  #     SERVICE_80_CHECK_HTTP: /
  #     SERVICE_80_CHECK_INTERVAL: 5s
  #     SERVICE_443_IGNORE: 'yes'
  #     SERVICE_TAGS: production
  #   networks:
  #     - back-tier

  # hello:
  #   image: lvlds/hello
  #   labels:
  #     SERVICE_80_NAME: http
  #     SERVICE_80_CHECK_HTTP: /
  #     SERVICE_80_CHECK_INTERVAL: 5s
  #     SERVICE_443_IGNORE: 'yes'
  #     SERVICE_TAGS: production
  #   networks:
  #     - back-tier


networks:
  back-tier:
    external:
      name: back-tier